include: package:very_good_analysis/analysis_options.yaml
analyzer:
  language:
    strict-casts: false

linter:
  rules:
    public_member_api_docs: false
    omit_local_variable_types: false
    always_put_required_named_parameters_first: false
