name: planning_poker_open
description: Planning poker app

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.12.0
  firebase_analytics: ^10.4.0
  firebase_crashlytics: ^3.3.0
  go_router: ^7.0.1
  flutter_bloc: ^8.1.2
  cloud_firestore: ^4.7.0
  firebase_auth: ^4.6.0
  equatable: ^2.0.5
  google_sign_in: ^6.1.0
  collection: ^1.17.1
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/