name: planning_poker_open
description: Planning poker app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_analytics: ^10.2.1
  firebase_crashlytics: ^3.1.2
  go_router: ^7.0.0
  flutter_bloc: ^8.1.2
  dropdown_button2: ^2.1.0
  cloud_firestore: ^4.5.3
  firebase_auth: ^4.4.2
  equatable: ^2.0.5
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0+1

flutter:

  uses-material-design: true
