// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiZsR0gUx3SBNXbUlzdV3Jmu7ORJZU0NY',
    appId: '1:607539426394:web:bc490b796a5c7efc04d463',
    messagingSenderId: '607539426394',
    projectId: 'planning-poker-open',
    authDomain: 'planning-poker-open.firebaseapp.com',
    storageBucket: 'planning-poker-open.appspot.com',
    measurementId: 'G-EQ2M4XBSPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF8s5K5qwel70ewEkEtaCN3sHXdx5r-Hs',
    appId: '1:607539426394:android:ef6cc8764bfb272804d463',
    messagingSenderId: '607539426394',
    projectId: 'planning-poker-open',
    storageBucket: 'planning-poker-open.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKRJezLs4VPvXc7WQYfL5Cd73NH47Zv14',
    appId: '1:607539426394:ios:17135455e9f80ae004d463',
    messagingSenderId: '607539426394',
    projectId: 'planning-poker-open',
    storageBucket: 'planning-poker-open.appspot.com',
    iosClientId: '607539426394-ma7n47m377qaiu07ck5gatgjjm58qd5m.apps.googleusercontent.com',
    iosBundleId: 'com.planningpokeropen.kdata.planningPokerOpen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKRJezLs4VPvXc7WQYfL5Cd73NH47Zv14',
    appId: '1:607539426394:ios:17135455e9f80ae004d463',
    messagingSenderId: '607539426394',
    projectId: 'planning-poker-open',
    storageBucket: 'planning-poker-open.appspot.com',
    iosClientId: '607539426394-ma7n47m377qaiu07ck5gatgjjm58qd5m.apps.googleusercontent.com',
    iosBundleId: 'com.planningpokeropen.kdata.planningPokerOpen',
  );
}
